services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lpw

  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8100:8100"
    depends_on:
      - db
    volumes:
      - shared_data:/shared           
    networks:
      - lpw

volumes:
  postgres_data:
  shared_data:  

networks:
  lpw:
    external: true